# Site settings
title: HSR - Semester Arbeit 2016 Log
email: 
description: Log für unsere Semster Arbeit an der HSR
baseurl: ""
url: "http://hsr-semester-arbeit2016.github.io"
twitter_username: 
github_username: HSR-Semester-Arbeit2016

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
