# Site settings
title: Simulating substance-influence in an AR/VR Cardboard-App
description: Student Research Project Thesis - HSR 2016
authors: Roberto Cuervo, Konrad Höpli
baseurl: ""
url: "http://hsr-semester-arbeit2016.github.io"
twitter_username: 
github_username: HSR-Semester-Arbeit2016

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
